//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 關聯性中繼資料

[assembly: EdmRelationshipAttribute("LedLocalModel", "FK_tblDevice_tblProjectGroupSection", "tblProjectGroupSection", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LedClientService.tblProjectGroupSection), "tblDevice", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LedClientService.tblDevice), true)]
[assembly: EdmRelationshipAttribute("LedLocalModel", "FK_tblProjectGroup_tblProject", "tblProject", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LedClientService.tblProject), "tblProjectGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LedClientService.tblProjectGroup), true)]
[assembly: EdmRelationshipAttribute("LedLocalModel", "FK_tblProjectGroupSection_tblProjectGroup", "tblProjectGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LedClientService.tblProjectGroup), "tblProjectGroupSection", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LedClientService.tblProjectGroupSection), true)]
[assembly: EdmRelationshipAttribute("LedLocalModel", "FK_tblSectionDailyPlan_tblProjectGroupSection", "tblProjectGroupSection", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LedClientService.tblProjectGroupSection), "tblSectionLedPlan", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LedClientService.tblSectionLedPlan), true)]
[assembly: EdmRelationshipAttribute("LedLocalModel", "FK_tblSectionLedOneTimePlan_tblProjectGroupSection", "tblProjectGroupSection", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LedClientService.tblProjectGroupSection), "tblSectionLedOneTimePlan", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LedClientService.tblSectionLedOneTimePlan), true)]

#endregion

namespace LedClientService
{
    #region 內容
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    public partial class LedLocalDb : ObjectContext
    {
        #region 建構函式
    
        /// <summary>
        /// 使用在應用程式組態檔的 'LedLocalDb' 區段中找到的連接字串，初始化新的 LedLocalDb 物件。
        /// </summary>
        public LedLocalDb() : base("name=LedLocalDb", "LedLocalDb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 LedLocalDb 物件。
        /// </summary>
        public LedLocalDb(string connectionString) : base(connectionString, "LedLocalDb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 LedLocalDb 物件。
        /// </summary>
        public LedLocalDb(EntityConnection connection) : base(connection, "LedLocalDb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblDevice> tblDevice
        {
            get
            {
                if ((_tblDevice == null))
                {
                    _tblDevice = base.CreateObjectSet<tblDevice>("tblDevice");
                }
                return _tblDevice;
            }
        }
        private ObjectSet<tblDevice> _tblDevice;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblProject> tblProject
        {
            get
            {
                if ((_tblProject == null))
                {
                    _tblProject = base.CreateObjectSet<tblProject>("tblProject");
                }
                return _tblProject;
            }
        }
        private ObjectSet<tblProject> _tblProject;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblProjectGroup> tblProjectGroup
        {
            get
            {
                if ((_tblProjectGroup == null))
                {
                    _tblProjectGroup = base.CreateObjectSet<tblProjectGroup>("tblProjectGroup");
                }
                return _tblProjectGroup;
            }
        }
        private ObjectSet<tblProjectGroup> _tblProjectGroup;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblProjectGroupSection> tblProjectGroupSection
        {
            get
            {
                if ((_tblProjectGroupSection == null))
                {
                    _tblProjectGroupSection = base.CreateObjectSet<tblProjectGroupSection>("tblProjectGroupSection");
                }
                return _tblProjectGroupSection;
            }
        }
        private ObjectSet<tblProjectGroupSection> _tblProjectGroupSection;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblSectionLedOneTimePlan> tblSectionLedOneTimePlan
        {
            get
            {
                if ((_tblSectionLedOneTimePlan == null))
                {
                    _tblSectionLedOneTimePlan = base.CreateObjectSet<tblSectionLedOneTimePlan>("tblSectionLedOneTimePlan");
                }
                return _tblSectionLedOneTimePlan;
            }
        }
        private ObjectSet<tblSectionLedOneTimePlan> _tblSectionLedOneTimePlan;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblSectionLedPlan> tblSectionLedPlan
        {
            get
            {
                if ((_tblSectionLedPlan == null))
                {
                    _tblSectionLedPlan = base.CreateObjectSet<tblSectionLedPlan>("tblSectionLedPlan");
                }
                return _tblSectionLedPlan;
            }
        }
        private ObjectSet<tblSectionLedPlan> _tblSectionLedPlan;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 將新物件加入 tblDevice EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblDevice(tblDevice tblDevice)
        {
            base.AddObject("tblDevice", tblDevice);
        }
    
        /// <summary>
        /// 將新物件加入 tblProject EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblProject(tblProject tblProject)
        {
            base.AddObject("tblProject", tblProject);
        }
    
        /// <summary>
        /// 將新物件加入 tblProjectGroup EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblProjectGroup(tblProjectGroup tblProjectGroup)
        {
            base.AddObject("tblProjectGroup", tblProjectGroup);
        }
    
        /// <summary>
        /// 將新物件加入 tblProjectGroupSection EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblProjectGroupSection(tblProjectGroupSection tblProjectGroupSection)
        {
            base.AddObject("tblProjectGroupSection", tblProjectGroupSection);
        }
    
        /// <summary>
        /// 將新物件加入 tblSectionLedOneTimePlan EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblSectionLedOneTimePlan(tblSectionLedOneTimePlan tblSectionLedOneTimePlan)
        {
            base.AddObject("tblSectionLedOneTimePlan", tblSectionLedOneTimePlan);
        }
    
        /// <summary>
        /// 將新物件加入 tblSectionLedPlan EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblSectionLedPlan(tblSectionLedPlan tblSectionLedPlan)
        {
            base.AddObject("tblSectionLedPlan", tblSectionLedPlan);
        }

        #endregion

    }

    #endregion

    #region 實體
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LedLocalModel", Name="tblDevice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblDevice : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblDevice 物件。
        /// </summary>
        /// <param name="projectID">ProjectID 屬性的初始值。</param>
        /// <param name="groupID">GroupID 屬性的初始值。</param>
        /// <param name="sectionID">SectionID 屬性的初始值。</param>
        /// <param name="deviceID">DeviceID 屬性的初始值。</param>
        /// <param name="shape">Shape 屬性的初始值。</param>
        /// <param name="rotation">Rotation 屬性的初始值。</param>
        /// <param name="devType">DevType 屬性的初始值。</param>
        /// <param name="x">X 屬性的初始值。</param>
        /// <param name="y">Y 屬性的初始值。</param>
        public static tblDevice CreatetblDevice(global::System.Int32 projectID, global::System.Int32 groupID, global::System.Int32 sectionID, global::System.Int32 deviceID, global::System.String shape, global::System.Double rotation, global::System.String devType, global::System.Int32 x, global::System.Int32 y)
        {
            tblDevice tblDevice = new tblDevice();
            tblDevice.ProjectID = projectID;
            tblDevice.GroupID = groupID;
            tblDevice.SectionID = sectionID;
            tblDevice.DeviceID = deviceID;
            tblDevice.Shape = shape;
            tblDevice.Rotation = rotation;
            tblDevice.DevType = devType;
            tblDevice.X = x;
            tblDevice.Y = y;
            return tblDevice;
        }

        #endregion

        #region 簡單屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProjectID
        {
            get
            {
                return _ProjectID;
            }
            set
            {
                if (_ProjectID != value)
                {
                    OnProjectIDChanging(value);
                    ReportPropertyChanging("ProjectID");
                    _ProjectID = StructuralObject.SetValidValue(value, "ProjectID");
                    ReportPropertyChanged("ProjectID");
                    OnProjectIDChanged();
                }
            }
        }
        private global::System.Int32 _ProjectID;
        partial void OnProjectIDChanging(global::System.Int32 value);
        partial void OnProjectIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                if (_GroupID != value)
                {
                    OnGroupIDChanging(value);
                    ReportPropertyChanging("GroupID");
                    _GroupID = StructuralObject.SetValidValue(value, "GroupID");
                    ReportPropertyChanged("GroupID");
                    OnGroupIDChanged();
                }
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SectionID
        {
            get
            {
                return _SectionID;
            }
            set
            {
                if (_SectionID != value)
                {
                    OnSectionIDChanging(value);
                    ReportPropertyChanging("SectionID");
                    _SectionID = StructuralObject.SetValidValue(value, "SectionID");
                    ReportPropertyChanged("SectionID");
                    OnSectionIDChanged();
                }
            }
        }
        private global::System.Int32 _SectionID;
        partial void OnSectionIDChanging(global::System.Int32 value);
        partial void OnSectionIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DeviceID
        {
            get
            {
                return _DeviceID;
            }
            set
            {
                if (_DeviceID != value)
                {
                    OnDeviceIDChanging(value);
                    ReportPropertyChanging("DeviceID");
                    _DeviceID = StructuralObject.SetValidValue(value, "DeviceID");
                    ReportPropertyChanged("DeviceID");
                    OnDeviceIDChanged();
                }
            }
        }
        private global::System.Int32 _DeviceID;
        partial void OnDeviceIDChanging(global::System.Int32 value);
        partial void OnDeviceIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Shape
        {
            get
            {
                return _Shape;
            }
            set
            {
                OnShapeChanging(value);
                ReportPropertyChanging("Shape");
                _Shape = StructuralObject.SetValidValue(value, false, "Shape");
                ReportPropertyChanged("Shape");
                OnShapeChanged();
            }
        }
        private global::System.String _Shape;
        partial void OnShapeChanging(global::System.String value);
        partial void OnShapeChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Rotation
        {
            get
            {
                return _Rotation;
            }
            set
            {
                OnRotationChanging(value);
                ReportPropertyChanging("Rotation");
                _Rotation = StructuralObject.SetValidValue(value, "Rotation");
                ReportPropertyChanged("Rotation");
                OnRotationChanged();
            }
        }
        private global::System.Double _Rotation;
        partial void OnRotationChanging(global::System.Double value);
        partial void OnRotationChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DevType
        {
            get
            {
                return _DevType;
            }
            set
            {
                OnDevTypeChanging(value);
                ReportPropertyChanging("DevType");
                _DevType = StructuralObject.SetValidValue(value, false, "DevType");
                ReportPropertyChanged("DevType");
                OnDevTypeChanged();
            }
        }
        private global::System.String _DevType;
        partial void OnDevTypeChanging(global::System.String value);
        partial void OnDevTypeChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ZeeBeeID
        {
            get
            {
                return _ZeeBeeID;
            }
            set
            {
                OnZeeBeeIDChanging(value);
                ReportPropertyChanging("ZeeBeeID");
                _ZeeBeeID = StructuralObject.SetValidValue(value, "ZeeBeeID");
                ReportPropertyChanged("ZeeBeeID");
                OnZeeBeeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ZeeBeeID;
        partial void OnZeeBeeIDChanging(Nullable<global::System.Int32> value);
        partial void OnZeeBeeIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 X
        {
            get
            {
                return _X;
            }
            set
            {
                OnXChanging(value);
                ReportPropertyChanging("X");
                _X = StructuralObject.SetValidValue(value, "X");
                ReportPropertyChanged("X");
                OnXChanged();
            }
        }
        private global::System.Int32 _X;
        partial void OnXChanging(global::System.Int32 value);
        partial void OnXChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Y
        {
            get
            {
                return _Y;
            }
            set
            {
                OnYChanging(value);
                ReportPropertyChanging("Y");
                _Y = StructuralObject.SetValidValue(value, "Y");
                ReportPropertyChanged("Y");
                OnYChanged();
            }
        }
        private global::System.Int32 _Y;
        partial void OnYChanging(global::System.Int32 value);
        partial void OnYChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ColorType
        {
            get
            {
                return _ColorType;
            }
            set
            {
                OnColorTypeChanging(value);
                ReportPropertyChanging("ColorType");
                _ColorType = StructuralObject.SetValidValue(value, true, "ColorType");
                ReportPropertyChanged("ColorType");
                OnColorTypeChanged();
            }
        }
        private global::System.String _ColorType;
        partial void OnColorTypeChanging(global::System.String value);
        partial void OnColorTypeChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MAC
        {
            get
            {
                return _MAC;
            }
            set
            {
                OnMACChanging(value);
                ReportPropertyChanging("MAC");
                _MAC = StructuralObject.SetValidValue(value, true, "MAC");
                ReportPropertyChanged("MAC");
                OnMACChanged();
            }
        }
        private global::System.String _MAC;
        partial void OnMACChanging(global::System.String value);
        partial void OnMACChanged();

        #endregion

        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LedLocalModel", "FK_tblDevice_tblProjectGroupSection", "tblProjectGroupSection")]
        public tblProjectGroupSection tblProjectGroupSection
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProjectGroupSection>("LedLocalModel.FK_tblDevice_tblProjectGroupSection", "tblProjectGroupSection").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProjectGroupSection>("LedLocalModel.FK_tblDevice_tblProjectGroupSection", "tblProjectGroupSection").Value = value;
            }
        }
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblProjectGroupSection> tblProjectGroupSectionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProjectGroupSection>("LedLocalModel.FK_tblDevice_tblProjectGroupSection", "tblProjectGroupSection");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblProjectGroupSection>("LedLocalModel.FK_tblDevice_tblProjectGroupSection", "tblProjectGroupSection", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LedLocalModel", Name="tblProject")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblProject : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblProject 物件。
        /// </summary>
        /// <param name="projectID">ProjectID 屬性的初始值。</param>
        /// <param name="projectName">ProjectName 屬性的初始值。</param>
        public static tblProject CreatetblProject(global::System.Int32 projectID, global::System.String projectName)
        {
            tblProject tblProject = new tblProject();
            tblProject.ProjectID = projectID;
            tblProject.ProjectName = projectName;
            return tblProject;
        }

        #endregion

        #region 簡單屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProjectID
        {
            get
            {
                return _ProjectID;
            }
            set
            {
                if (_ProjectID != value)
                {
                    OnProjectIDChanging(value);
                    ReportPropertyChanging("ProjectID");
                    _ProjectID = StructuralObject.SetValidValue(value, "ProjectID");
                    ReportPropertyChanged("ProjectID");
                    OnProjectIDChanged();
                }
            }
        }
        private global::System.Int32 _ProjectID;
        partial void OnProjectIDChanging(global::System.Int32 value);
        partial void OnProjectIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProjectName
        {
            get
            {
                return _ProjectName;
            }
            set
            {
                OnProjectNameChanging(value);
                ReportPropertyChanging("ProjectName");
                _ProjectName = StructuralObject.SetValidValue(value, false, "ProjectName");
                ReportPropertyChanged("ProjectName");
                OnProjectNameChanged();
            }
        }
        private global::System.String _ProjectName;
        partial void OnProjectNameChanging(global::System.String value);
        partial void OnProjectNameChanged();

        #endregion

        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LedLocalModel", "FK_tblProjectGroup_tblProject", "tblProjectGroup")]
        public EntityCollection<tblProjectGroup> tblProjectGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblProjectGroup>("LedLocalModel.FK_tblProjectGroup_tblProject", "tblProjectGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblProjectGroup>("LedLocalModel.FK_tblProjectGroup_tblProject", "tblProjectGroup", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LedLocalModel", Name="tblProjectGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblProjectGroup : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblProjectGroup 物件。
        /// </summary>
        /// <param name="projectID">ProjectID 屬性的初始值。</param>
        /// <param name="groupID">GroupID 屬性的初始值。</param>
        public static tblProjectGroup CreatetblProjectGroup(global::System.Int32 projectID, global::System.Int32 groupID)
        {
            tblProjectGroup tblProjectGroup = new tblProjectGroup();
            tblProjectGroup.ProjectID = projectID;
            tblProjectGroup.GroupID = groupID;
            return tblProjectGroup;
        }

        #endregion

        #region 簡單屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProjectID
        {
            get
            {
                return _ProjectID;
            }
            set
            {
                if (_ProjectID != value)
                {
                    OnProjectIDChanging(value);
                    ReportPropertyChanging("ProjectID");
                    _ProjectID = StructuralObject.SetValidValue(value, "ProjectID");
                    ReportPropertyChanged("ProjectID");
                    OnProjectIDChanged();
                }
            }
        }
        private global::System.Int32 _ProjectID;
        partial void OnProjectIDChanging(global::System.Int32 value);
        partial void OnProjectIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                if (_GroupID != value)
                {
                    OnGroupIDChanging(value);
                    ReportPropertyChanging("GroupID");
                    _GroupID = StructuralObject.SetValidValue(value, "GroupID");
                    ReportPropertyChanged("GroupID");
                    OnGroupIDChanged();
                }
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GroupName
        {
            get
            {
                return _GroupName;
            }
            set
            {
                OnGroupNameChanging(value);
                ReportPropertyChanging("GroupName");
                _GroupName = StructuralObject.SetValidValue(value, true, "GroupName");
                ReportPropertyChanged("GroupName");
                OnGroupNameChanged();
            }
        }
        private global::System.String _GroupName;
        partial void OnGroupNameChanging(global::System.String value);
        partial void OnGroupNameChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GroupPicture
        {
            get
            {
                return _GroupPicture;
            }
            set
            {
                OnGroupPictureChanging(value);
                ReportPropertyChanging("GroupPicture");
                _GroupPicture = StructuralObject.SetValidValue(value, true, "GroupPicture");
                ReportPropertyChanged("GroupPicture");
                OnGroupPictureChanged();
            }
        }
        private global::System.String _GroupPicture;
        partial void OnGroupPictureChanging(global::System.String value);
        partial void OnGroupPictureChanged();

        #endregion

        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LedLocalModel", "FK_tblProjectGroup_tblProject", "tblProject")]
        public tblProject tblProject
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProject>("LedLocalModel.FK_tblProjectGroup_tblProject", "tblProject").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProject>("LedLocalModel.FK_tblProjectGroup_tblProject", "tblProject").Value = value;
            }
        }
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblProject> tblProjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProject>("LedLocalModel.FK_tblProjectGroup_tblProject", "tblProject");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblProject>("LedLocalModel.FK_tblProjectGroup_tblProject", "tblProject", value);
                }
            }
        }
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LedLocalModel", "FK_tblProjectGroupSection_tblProjectGroup", "tblProjectGroupSection")]
        public EntityCollection<tblProjectGroupSection> tblProjectGroupSection
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblProjectGroupSection>("LedLocalModel.FK_tblProjectGroupSection_tblProjectGroup", "tblProjectGroupSection");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblProjectGroupSection>("LedLocalModel.FK_tblProjectGroupSection_tblProjectGroup", "tblProjectGroupSection", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LedLocalModel", Name="tblProjectGroupSection")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblProjectGroupSection : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblProjectGroupSection 物件。
        /// </summary>
        /// <param name="projectID">ProjectID 屬性的初始值。</param>
        /// <param name="groupID">GroupID 屬性的初始值。</param>
        /// <param name="sectionID">SectionID 屬性的初始值。</param>
        /// <param name="sectionName">SectionName 屬性的初始值。</param>
        public static tblProjectGroupSection CreatetblProjectGroupSection(global::System.Int32 projectID, global::System.Int32 groupID, global::System.Int32 sectionID, global::System.String sectionName)
        {
            tblProjectGroupSection tblProjectGroupSection = new tblProjectGroupSection();
            tblProjectGroupSection.ProjectID = projectID;
            tblProjectGroupSection.GroupID = groupID;
            tblProjectGroupSection.SectionID = sectionID;
            tblProjectGroupSection.SectionName = sectionName;
            return tblProjectGroupSection;
        }

        #endregion

        #region 簡單屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProjectID
        {
            get
            {
                return _ProjectID;
            }
            set
            {
                if (_ProjectID != value)
                {
                    OnProjectIDChanging(value);
                    ReportPropertyChanging("ProjectID");
                    _ProjectID = StructuralObject.SetValidValue(value, "ProjectID");
                    ReportPropertyChanged("ProjectID");
                    OnProjectIDChanged();
                }
            }
        }
        private global::System.Int32 _ProjectID;
        partial void OnProjectIDChanging(global::System.Int32 value);
        partial void OnProjectIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                if (_GroupID != value)
                {
                    OnGroupIDChanging(value);
                    ReportPropertyChanging("GroupID");
                    _GroupID = StructuralObject.SetValidValue(value, "GroupID");
                    ReportPropertyChanged("GroupID");
                    OnGroupIDChanged();
                }
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SectionID
        {
            get
            {
                return _SectionID;
            }
            set
            {
                if (_SectionID != value)
                {
                    OnSectionIDChanging(value);
                    ReportPropertyChanging("SectionID");
                    _SectionID = StructuralObject.SetValidValue(value, "SectionID");
                    ReportPropertyChanged("SectionID");
                    OnSectionIDChanged();
                }
            }
        }
        private global::System.Int32 _SectionID;
        partial void OnSectionIDChanging(global::System.Int32 value);
        partial void OnSectionIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SectionName
        {
            get
            {
                return _SectionName;
            }
            set
            {
                OnSectionNameChanging(value);
                ReportPropertyChanging("SectionName");
                _SectionName = StructuralObject.SetValidValue(value, false, "SectionName");
                ReportPropertyChanged("SectionName");
                OnSectionNameChanged();
            }
        }
        private global::System.String _SectionName;
        partial void OnSectionNameChanging(global::System.String value);
        partial void OnSectionNameChanged();

        #endregion

        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LedLocalModel", "FK_tblDevice_tblProjectGroupSection", "tblDevice")]
        public EntityCollection<tblDevice> tblDevice
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblDevice>("LedLocalModel.FK_tblDevice_tblProjectGroupSection", "tblDevice");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblDevice>("LedLocalModel.FK_tblDevice_tblProjectGroupSection", "tblDevice", value);
                }
            }
        }
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LedLocalModel", "FK_tblProjectGroupSection_tblProjectGroup", "tblProjectGroup")]
        public tblProjectGroup tblProjectGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProjectGroup>("LedLocalModel.FK_tblProjectGroupSection_tblProjectGroup", "tblProjectGroup").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProjectGroup>("LedLocalModel.FK_tblProjectGroupSection_tblProjectGroup", "tblProjectGroup").Value = value;
            }
        }
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblProjectGroup> tblProjectGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProjectGroup>("LedLocalModel.FK_tblProjectGroupSection_tblProjectGroup", "tblProjectGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblProjectGroup>("LedLocalModel.FK_tblProjectGroupSection_tblProjectGroup", "tblProjectGroup", value);
                }
            }
        }
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LedLocalModel", "FK_tblSectionDailyPlan_tblProjectGroupSection", "tblSectionLedPlan")]
        public EntityCollection<tblSectionLedPlan> tblSectionLedPlan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblSectionLedPlan>("LedLocalModel.FK_tblSectionDailyPlan_tblProjectGroupSection", "tblSectionLedPlan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblSectionLedPlan>("LedLocalModel.FK_tblSectionDailyPlan_tblProjectGroupSection", "tblSectionLedPlan", value);
                }
            }
        }
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LedLocalModel", "FK_tblSectionLedOneTimePlan_tblProjectGroupSection", "tblSectionLedOneTimePlan")]
        public EntityCollection<tblSectionLedOneTimePlan> tblSectionLedOneTimePlan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblSectionLedOneTimePlan>("LedLocalModel.FK_tblSectionLedOneTimePlan_tblProjectGroupSection", "tblSectionLedOneTimePlan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblSectionLedOneTimePlan>("LedLocalModel.FK_tblSectionLedOneTimePlan_tblProjectGroupSection", "tblSectionLedOneTimePlan", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LedLocalModel", Name="tblSectionLedOneTimePlan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSectionLedOneTimePlan : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblSectionLedOneTimePlan 物件。
        /// </summary>
        /// <param name="projectID">ProjectID 屬性的初始值。</param>
        /// <param name="groupID">GroupID 屬性的初始值。</param>
        /// <param name="sectionID">SectionID 屬性的初始值。</param>
        /// <param name="planID">PlanID 屬性的初始值。</param>
        /// <param name="w">W 屬性的初始值。</param>
        /// <param name="r">R 屬性的初始值。</param>
        /// <param name="g">G 屬性的初始值。</param>
        /// <param name="b">B 屬性的初始值。</param>
        /// <param name="beginTime">BeginTime 屬性的初始值。</param>
        /// <param name="durationMin">DurationMin 屬性的初始值。</param>
        public static tblSectionLedOneTimePlan CreatetblSectionLedOneTimePlan(global::System.Int32 projectID, global::System.Int32 groupID, global::System.Int32 sectionID, global::System.Int32 planID, global::System.Int32 w, global::System.Int32 r, global::System.Int32 g, global::System.Int32 b, global::System.DateTime beginTime, global::System.Int32 durationMin)
        {
            tblSectionLedOneTimePlan tblSectionLedOneTimePlan = new tblSectionLedOneTimePlan();
            tblSectionLedOneTimePlan.ProjectID = projectID;
            tblSectionLedOneTimePlan.GroupID = groupID;
            tblSectionLedOneTimePlan.SectionID = sectionID;
            tblSectionLedOneTimePlan.PlanID = planID;
            tblSectionLedOneTimePlan.W = w;
            tblSectionLedOneTimePlan.R = r;
            tblSectionLedOneTimePlan.G = g;
            tblSectionLedOneTimePlan.B = b;
            tblSectionLedOneTimePlan.BeginTime = beginTime;
            tblSectionLedOneTimePlan.DurationMin = durationMin;
            return tblSectionLedOneTimePlan;
        }

        #endregion

        #region 簡單屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProjectID
        {
            get
            {
                return _ProjectID;
            }
            set
            {
                if (_ProjectID != value)
                {
                    OnProjectIDChanging(value);
                    ReportPropertyChanging("ProjectID");
                    _ProjectID = StructuralObject.SetValidValue(value, "ProjectID");
                    ReportPropertyChanged("ProjectID");
                    OnProjectIDChanged();
                }
            }
        }
        private global::System.Int32 _ProjectID;
        partial void OnProjectIDChanging(global::System.Int32 value);
        partial void OnProjectIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                if (_GroupID != value)
                {
                    OnGroupIDChanging(value);
                    ReportPropertyChanging("GroupID");
                    _GroupID = StructuralObject.SetValidValue(value, "GroupID");
                    ReportPropertyChanged("GroupID");
                    OnGroupIDChanged();
                }
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SectionID
        {
            get
            {
                return _SectionID;
            }
            set
            {
                if (_SectionID != value)
                {
                    OnSectionIDChanging(value);
                    ReportPropertyChanging("SectionID");
                    _SectionID = StructuralObject.SetValidValue(value, "SectionID");
                    ReportPropertyChanged("SectionID");
                    OnSectionIDChanged();
                }
            }
        }
        private global::System.Int32 _SectionID;
        partial void OnSectionIDChanging(global::System.Int32 value);
        partial void OnSectionIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlanID
        {
            get
            {
                return _PlanID;
            }
            set
            {
                if (_PlanID != value)
                {
                    OnPlanIDChanging(value);
                    ReportPropertyChanging("PlanID");
                    _PlanID = StructuralObject.SetValidValue(value, "PlanID");
                    ReportPropertyChanged("PlanID");
                    OnPlanIDChanged();
                }
            }
        }
        private global::System.Int32 _PlanID;
        partial void OnPlanIDChanging(global::System.Int32 value);
        partial void OnPlanIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 W
        {
            get
            {
                return _W;
            }
            set
            {
                OnWChanging(value);
                ReportPropertyChanging("W");
                _W = StructuralObject.SetValidValue(value, "W");
                ReportPropertyChanged("W");
                OnWChanged();
            }
        }
        private global::System.Int32 _W;
        partial void OnWChanging(global::System.Int32 value);
        partial void OnWChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 R
        {
            get
            {
                return _R;
            }
            set
            {
                OnRChanging(value);
                ReportPropertyChanging("R");
                _R = StructuralObject.SetValidValue(value, "R");
                ReportPropertyChanged("R");
                OnRChanged();
            }
        }
        private global::System.Int32 _R;
        partial void OnRChanging(global::System.Int32 value);
        partial void OnRChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 G
        {
            get
            {
                return _G;
            }
            set
            {
                OnGChanging(value);
                ReportPropertyChanging("G");
                _G = StructuralObject.SetValidValue(value, "G");
                ReportPropertyChanged("G");
                OnGChanged();
            }
        }
        private global::System.Int32 _G;
        partial void OnGChanging(global::System.Int32 value);
        partial void OnGChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 B
        {
            get
            {
                return _B;
            }
            set
            {
                OnBChanging(value);
                ReportPropertyChanging("B");
                _B = StructuralObject.SetValidValue(value, "B");
                ReportPropertyChanged("B");
                OnBChanged();
            }
        }
        private global::System.Int32 _B;
        partial void OnBChanging(global::System.Int32 value);
        partial void OnBChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime BeginTime
        {
            get
            {
                return _BeginTime;
            }
            set
            {
                OnBeginTimeChanging(value);
                ReportPropertyChanging("BeginTime");
                _BeginTime = StructuralObject.SetValidValue(value, "BeginTime");
                ReportPropertyChanged("BeginTime");
                OnBeginTimeChanged();
            }
        }
        private global::System.DateTime _BeginTime;
        partial void OnBeginTimeChanging(global::System.DateTime value);
        partial void OnBeginTimeChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DurationMin
        {
            get
            {
                return _DurationMin;
            }
            set
            {
                OnDurationMinChanging(value);
                ReportPropertyChanging("DurationMin");
                _DurationMin = StructuralObject.SetValidValue(value, "DurationMin");
                ReportPropertyChanged("DurationMin");
                OnDurationMinChanged();
            }
        }
        private global::System.Int32 _DurationMin;
        partial void OnDurationMinChanging(global::System.Int32 value);
        partial void OnDurationMinChanged();

        #endregion

        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LedLocalModel", "FK_tblSectionLedOneTimePlan_tblProjectGroupSection", "tblProjectGroupSection")]
        public tblProjectGroupSection tblProjectGroupSection
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProjectGroupSection>("LedLocalModel.FK_tblSectionLedOneTimePlan_tblProjectGroupSection", "tblProjectGroupSection").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProjectGroupSection>("LedLocalModel.FK_tblSectionLedOneTimePlan_tblProjectGroupSection", "tblProjectGroupSection").Value = value;
            }
        }
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblProjectGroupSection> tblProjectGroupSectionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProjectGroupSection>("LedLocalModel.FK_tblSectionLedOneTimePlan_tblProjectGroupSection", "tblProjectGroupSection");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblProjectGroupSection>("LedLocalModel.FK_tblSectionLedOneTimePlan_tblProjectGroupSection", "tblProjectGroupSection", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LedLocalModel", Name="tblSectionLedPlan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSectionLedPlan : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblSectionLedPlan 物件。
        /// </summary>
        /// <param name="projectID">ProjectID 屬性的初始值。</param>
        /// <param name="groupID">GroupID 屬性的初始值。</param>
        /// <param name="sectionID">SectionID 屬性的初始值。</param>
        /// <param name="planID">PlanID 屬性的初始值。</param>
        /// <param name="beginTime">BeginTime 屬性的初始值。</param>
        /// <param name="w">W 屬性的初始值。</param>
        /// <param name="r">R 屬性的初始值。</param>
        /// <param name="g">G 屬性的初始值。</param>
        /// <param name="b">B 屬性的初始值。</param>
        public static tblSectionLedPlan CreatetblSectionLedPlan(global::System.Int32 projectID, global::System.Int32 groupID, global::System.Int32 sectionID, global::System.Int32 planID, global::System.DateTime beginTime, global::System.Int32 w, global::System.Int32 r, global::System.Int32 g, global::System.Int32 b)
        {
            tblSectionLedPlan tblSectionLedPlan = new tblSectionLedPlan();
            tblSectionLedPlan.ProjectID = projectID;
            tblSectionLedPlan.GroupID = groupID;
            tblSectionLedPlan.SectionID = sectionID;
            tblSectionLedPlan.PlanID = planID;
            tblSectionLedPlan.BeginTime = beginTime;
            tblSectionLedPlan.W = w;
            tblSectionLedPlan.R = r;
            tblSectionLedPlan.G = g;
            tblSectionLedPlan.B = b;
            return tblSectionLedPlan;
        }

        #endregion

        #region 簡單屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProjectID
        {
            get
            {
                return _ProjectID;
            }
            set
            {
                if (_ProjectID != value)
                {
                    OnProjectIDChanging(value);
                    ReportPropertyChanging("ProjectID");
                    _ProjectID = StructuralObject.SetValidValue(value, "ProjectID");
                    ReportPropertyChanged("ProjectID");
                    OnProjectIDChanged();
                }
            }
        }
        private global::System.Int32 _ProjectID;
        partial void OnProjectIDChanging(global::System.Int32 value);
        partial void OnProjectIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                if (_GroupID != value)
                {
                    OnGroupIDChanging(value);
                    ReportPropertyChanging("GroupID");
                    _GroupID = StructuralObject.SetValidValue(value, "GroupID");
                    ReportPropertyChanged("GroupID");
                    OnGroupIDChanged();
                }
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SectionID
        {
            get
            {
                return _SectionID;
            }
            set
            {
                if (_SectionID != value)
                {
                    OnSectionIDChanging(value);
                    ReportPropertyChanging("SectionID");
                    _SectionID = StructuralObject.SetValidValue(value, "SectionID");
                    ReportPropertyChanged("SectionID");
                    OnSectionIDChanged();
                }
            }
        }
        private global::System.Int32 _SectionID;
        partial void OnSectionIDChanging(global::System.Int32 value);
        partial void OnSectionIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlanID
        {
            get
            {
                return _PlanID;
            }
            set
            {
                if (_PlanID != value)
                {
                    OnPlanIDChanging(value);
                    ReportPropertyChanging("PlanID");
                    _PlanID = StructuralObject.SetValidValue(value, "PlanID");
                    ReportPropertyChanged("PlanID");
                    OnPlanIDChanged();
                }
            }
        }
        private global::System.Int32 _PlanID;
        partial void OnPlanIDChanging(global::System.Int32 value);
        partial void OnPlanIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime BeginTime
        {
            get
            {
                return _BeginTime;
            }
            set
            {
                OnBeginTimeChanging(value);
                ReportPropertyChanging("BeginTime");
                _BeginTime = StructuralObject.SetValidValue(value, "BeginTime");
                ReportPropertyChanged("BeginTime");
                OnBeginTimeChanged();
            }
        }
        private global::System.DateTime _BeginTime;
        partial void OnBeginTimeChanging(global::System.DateTime value);
        partial void OnBeginTimeChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 W
        {
            get
            {
                return _W;
            }
            set
            {
                OnWChanging(value);
                ReportPropertyChanging("W");
                _W = StructuralObject.SetValidValue(value, "W");
                ReportPropertyChanged("W");
                OnWChanged();
            }
        }
        private global::System.Int32 _W;
        partial void OnWChanging(global::System.Int32 value);
        partial void OnWChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 R
        {
            get
            {
                return _R;
            }
            set
            {
                OnRChanging(value);
                ReportPropertyChanging("R");
                _R = StructuralObject.SetValidValue(value, "R");
                ReportPropertyChanged("R");
                OnRChanged();
            }
        }
        private global::System.Int32 _R;
        partial void OnRChanging(global::System.Int32 value);
        partial void OnRChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 G
        {
            get
            {
                return _G;
            }
            set
            {
                OnGChanging(value);
                ReportPropertyChanging("G");
                _G = StructuralObject.SetValidValue(value, "G");
                ReportPropertyChanged("G");
                OnGChanged();
            }
        }
        private global::System.Int32 _G;
        partial void OnGChanging(global::System.Int32 value);
        partial void OnGChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 B
        {
            get
            {
                return _B;
            }
            set
            {
                OnBChanging(value);
                ReportPropertyChanging("B");
                _B = StructuralObject.SetValidValue(value, "B");
                ReportPropertyChanged("B");
                OnBChanged();
            }
        }
        private global::System.Int32 _B;
        partial void OnBChanging(global::System.Int32 value);
        partial void OnBChanged();

        #endregion

        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LedLocalModel", "FK_tblSectionDailyPlan_tblProjectGroupSection", "tblProjectGroupSection")]
        public tblProjectGroupSection tblProjectGroupSection
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProjectGroupSection>("LedLocalModel.FK_tblSectionDailyPlan_tblProjectGroupSection", "tblProjectGroupSection").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProjectGroupSection>("LedLocalModel.FK_tblSectionDailyPlan_tblProjectGroupSection", "tblProjectGroupSection").Value = value;
            }
        }
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblProjectGroupSection> tblProjectGroupSectionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProjectGroupSection>("LedLocalModel.FK_tblSectionDailyPlan_tblProjectGroupSection", "tblProjectGroupSection");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblProjectGroupSection>("LedLocalModel.FK_tblSectionDailyPlan_tblProjectGroupSection", "tblProjectGroupSection", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
