//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18051
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 原始檔案名稱:
// 產生日期: 2013/10/11 下午 01:10:08
namespace LedClientService.LedDataService
{
    
    /// <summary>
    /// 結構描述中沒有 DB 的註解。
    /// </summary>
    public partial class DB : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// 初始化新的 DB 物件。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DB(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// 因為在 Visual Studio 中為這個服務參考設定的
        /// 命名空間與伺服器結構描述中指示的命名空間
        /// 不同，請使用型別對應程式對應這兩者。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("LEDProjecctModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("LedClientService.LedDataService", typeName.Substring(16)), false);
            }
            return null;
        }
        /// <summary>
        /// 因為在 Visual Studio 中為這個服務參考設定的
        /// 命名空間與伺服器結構描述中指示的命名空間
        /// 不同，請使用型別對應程式對應這兩者。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LedClientService.LedDataService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LEDProjecctModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// 結構描述中沒有 tblDevice 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<tblDevice> tblDevice
        {
            get
            {
                if ((this._tblDevice == null))
                {
                    this._tblDevice = base.CreateQuery<tblDevice>("tblDevice");
                }
                return this._tblDevice;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<tblDevice> _tblDevice;
        /// <summary>
        /// 結構描述中沒有 tblProject 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<tblProject> tblProject
        {
            get
            {
                if ((this._tblProject == null))
                {
                    this._tblProject = base.CreateQuery<tblProject>("tblProject");
                }
                return this._tblProject;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<tblProject> _tblProject;
        /// <summary>
        /// 結構描述中沒有 tblProjectGroup 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<tblProjectGroup> tblProjectGroup
        {
            get
            {
                if ((this._tblProjectGroup == null))
                {
                    this._tblProjectGroup = base.CreateQuery<tblProjectGroup>("tblProjectGroup");
                }
                return this._tblProjectGroup;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<tblProjectGroup> _tblProjectGroup;
        /// <summary>
        /// 結構描述中沒有 tblProjectGroupSection 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<tblProjectGroupSection> tblProjectGroupSection
        {
            get
            {
                if ((this._tblProjectGroupSection == null))
                {
                    this._tblProjectGroupSection = base.CreateQuery<tblProjectGroupSection>("tblProjectGroupSection");
                }
                return this._tblProjectGroupSection;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<tblProjectGroupSection> _tblProjectGroupSection;
        /// <summary>
        /// 結構描述中沒有 tblDevice 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTotblDevice(tblDevice tblDevice)
        {
            base.AddObject("tblDevice", tblDevice);
        }
        /// <summary>
        /// 結構描述中沒有 tblProject 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTotblProject(tblProject tblProject)
        {
            base.AddObject("tblProject", tblProject);
        }
        /// <summary>
        /// 結構描述中沒有 tblProjectGroup 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTotblProjectGroup(tblProjectGroup tblProjectGroup)
        {
            base.AddObject("tblProjectGroup", tblProjectGroup);
        }
        /// <summary>
        /// 結構描述中沒有 tblProjectGroupSection 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTotblProjectGroupSection(tblProjectGroupSection tblProjectGroupSection)
        {
            base.AddObject("tblProjectGroupSection", tblProjectGroupSection);
        }
    }
    /// <summary>
    /// 結構描述中沒有 LEDProjecctModel.tblDevice 的註解。
    /// </summary>
    /// <KeyProperties>
    /// ProjectID
    /// GroupID
    /// SectionID
    /// DeviceID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("tblDevice")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ProjectID", "GroupID", "SectionID", "DeviceID")]
    public partial class tblDevice : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 建立新的 tblDevice 物件。
        /// </summary>
        /// <param name="projectID">ProjectID 的初始值。</param>
        /// <param name="groupID">GroupID 的初始值。</param>
        /// <param name="sectionID">SectionID 的初始值。</param>
        /// <param name="deviceID">DeviceID 的初始值。</param>
        /// <param name="shape">Shape 的初始值。</param>
        /// <param name="rotation">Rotation 的初始值。</param>
        /// <param name="devType">DevType 的初始值。</param>
        /// <param name="x">X 的初始值。</param>
        /// <param name="y">Y 的初始值。</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static tblDevice CreatetblDevice(int projectID, int groupID, int sectionID, int deviceID, string shape, double rotation, string devType, int x, int y)
        {
            tblDevice tblDevice = new tblDevice();
            tblDevice.ProjectID = projectID;
            tblDevice.GroupID = groupID;
            tblDevice.SectionID = sectionID;
            tblDevice.DeviceID = deviceID;
            tblDevice.Shape = shape;
            tblDevice.Rotation = rotation;
            tblDevice.DevType = devType;
            tblDevice.X = x;
            tblDevice.Y = y;
            return tblDevice;
        }
        /// <summary>
        /// 結構描述中沒有屬性 ProjectID 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProjectID
        {
            get
            {
                return this._ProjectID;
            }
            set
            {
                this.OnProjectIDChanging(value);
                this._ProjectID = value;
                this.OnProjectIDChanged();
                this.OnPropertyChanged("ProjectID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProjectID;
        partial void OnProjectIDChanging(int value);
        partial void OnProjectIDChanged();
        /// <summary>
        /// 結構描述中沒有屬性 GroupID 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int GroupID
        {
            get
            {
                return this._GroupID;
            }
            set
            {
                this.OnGroupIDChanging(value);
                this._GroupID = value;
                this.OnGroupIDChanged();
                this.OnPropertyChanged("GroupID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _GroupID;
        partial void OnGroupIDChanging(int value);
        partial void OnGroupIDChanged();
        /// <summary>
        /// 結構描述中沒有屬性 SectionID 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SectionID
        {
            get
            {
                return this._SectionID;
            }
            set
            {
                this.OnSectionIDChanging(value);
                this._SectionID = value;
                this.OnSectionIDChanged();
                this.OnPropertyChanged("SectionID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SectionID;
        partial void OnSectionIDChanging(int value);
        partial void OnSectionIDChanged();
        /// <summary>
        /// 結構描述中沒有屬性 DeviceID 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int DeviceID
        {
            get
            {
                return this._DeviceID;
            }
            set
            {
                this.OnDeviceIDChanging(value);
                this._DeviceID = value;
                this.OnDeviceIDChanged();
                this.OnPropertyChanged("DeviceID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _DeviceID;
        partial void OnDeviceIDChanging(int value);
        partial void OnDeviceIDChanged();
        /// <summary>
        /// 結構描述中沒有屬性 Shape 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Shape
        {
            get
            {
                return this._Shape;
            }
            set
            {
                this.OnShapeChanging(value);
                this._Shape = value;
                this.OnShapeChanged();
                this.OnPropertyChanged("Shape");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Shape;
        partial void OnShapeChanging(string value);
        partial void OnShapeChanged();
        /// <summary>
        /// 結構描述中沒有屬性 Rotation 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Rotation
        {
            get
            {
                return this._Rotation;
            }
            set
            {
                this.OnRotationChanging(value);
                this._Rotation = value;
                this.OnRotationChanged();
                this.OnPropertyChanged("Rotation");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Rotation;
        partial void OnRotationChanging(double value);
        partial void OnRotationChanged();
        /// <summary>
        /// 結構描述中沒有屬性 DevType 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DevType
        {
            get
            {
                return this._DevType;
            }
            set
            {
                this.OnDevTypeChanging(value);
                this._DevType = value;
                this.OnDevTypeChanged();
                this.OnPropertyChanged("DevType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DevType;
        partial void OnDevTypeChanging(string value);
        partial void OnDevTypeChanged();
        /// <summary>
        /// 結構描述中沒有屬性 ZeeBeeID 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ZeeBeeID
        {
            get
            {
                return this._ZeeBeeID;
            }
            set
            {
                this.OnZeeBeeIDChanging(value);
                this._ZeeBeeID = value;
                this.OnZeeBeeIDChanged();
                this.OnPropertyChanged("ZeeBeeID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ZeeBeeID;
        partial void OnZeeBeeIDChanging(global::System.Nullable<int> value);
        partial void OnZeeBeeIDChanged();
        /// <summary>
        /// 結構描述中沒有屬性 X 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int X
        {
            get
            {
                return this._X;
            }
            set
            {
                this.OnXChanging(value);
                this._X = value;
                this.OnXChanged();
                this.OnPropertyChanged("X");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _X;
        partial void OnXChanging(int value);
        partial void OnXChanged();
        /// <summary>
        /// 結構描述中沒有屬性 Y 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Y
        {
            get
            {
                return this._Y;
            }
            set
            {
                this.OnYChanging(value);
                this._Y = value;
                this.OnYChanged();
                this.OnPropertyChanged("Y");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Y;
        partial void OnYChanging(int value);
        partial void OnYChanged();
        /// <summary>
        /// 結構描述中沒有屬性 ColorType 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ColorType
        {
            get
            {
                return this._ColorType;
            }
            set
            {
                this.OnColorTypeChanging(value);
                this._ColorType = value;
                this.OnColorTypeChanged();
                this.OnPropertyChanged("ColorType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ColorType;
        partial void OnColorTypeChanging(string value);
        partial void OnColorTypeChanged();
        /// <summary>
        /// 結構描述中沒有屬性 MAC 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MAC
        {
            get
            {
                return this._MAC;
            }
            set
            {
                this.OnMACChanging(value);
                this._MAC = value;
                this.OnMACChanged();
                this.OnPropertyChanged("MAC");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MAC;
        partial void OnMACChanging(string value);
        partial void OnMACChanged();
        /// <summary>
        /// 結構描述中沒有 tblProjectGroupSection 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public tblProjectGroupSection tblProjectGroupSection
        {
            get
            {
                return this._tblProjectGroupSection;
            }
            set
            {
                this._tblProjectGroupSection = value;
                this.OnPropertyChanged("tblProjectGroupSection");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private tblProjectGroupSection _tblProjectGroupSection;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 結構描述中沒有 LEDProjecctModel.tblProject 的註解。
    /// </summary>
    /// <KeyProperties>
    /// ProjectID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("tblProject")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ProjectID")]
    public partial class tblProject : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 建立新的 tblProject 物件。
        /// </summary>
        /// <param name="projectID">ProjectID 的初始值。</param>
        /// <param name="projectName">ProjectName 的初始值。</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static tblProject CreatetblProject(int projectID, string projectName)
        {
            tblProject tblProject = new tblProject();
            tblProject.ProjectID = projectID;
            tblProject.ProjectName = projectName;
            return tblProject;
        }
        /// <summary>
        /// 結構描述中沒有屬性 ProjectID 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProjectID
        {
            get
            {
                return this._ProjectID;
            }
            set
            {
                this.OnProjectIDChanging(value);
                this._ProjectID = value;
                this.OnProjectIDChanged();
                this.OnPropertyChanged("ProjectID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProjectID;
        partial void OnProjectIDChanging(int value);
        partial void OnProjectIDChanged();
        /// <summary>
        /// 結構描述中沒有屬性 ProjectName 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProjectName
        {
            get
            {
                return this._ProjectName;
            }
            set
            {
                this.OnProjectNameChanging(value);
                this._ProjectName = value;
                this.OnProjectNameChanged();
                this.OnPropertyChanged("ProjectName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProjectName;
        partial void OnProjectNameChanging(string value);
        partial void OnProjectNameChanged();
        /// <summary>
        /// 結構描述中沒有 tblProjectGroup 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<tblProjectGroup> tblProjectGroup
        {
            get
            {
                return this._tblProjectGroup;
            }
            set
            {
                this._tblProjectGroup = value;
                this.OnPropertyChanged("tblProjectGroup");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<tblProjectGroup> _tblProjectGroup = new global::System.Data.Services.Client.DataServiceCollection<tblProjectGroup>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 結構描述中沒有 LEDProjecctModel.tblProjectGroup 的註解。
    /// </summary>
    /// <KeyProperties>
    /// ProjectID
    /// GroupID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("tblProjectGroup")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ProjectID", "GroupID")]
    public partial class tblProjectGroup : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 建立新的 tblProjectGroup 物件。
        /// </summary>
        /// <param name="projectID">ProjectID 的初始值。</param>
        /// <param name="groupID">GroupID 的初始值。</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static tblProjectGroup CreatetblProjectGroup(int projectID, int groupID)
        {
            tblProjectGroup tblProjectGroup = new tblProjectGroup();
            tblProjectGroup.ProjectID = projectID;
            tblProjectGroup.GroupID = groupID;
            return tblProjectGroup;
        }
        /// <summary>
        /// 結構描述中沒有屬性 ProjectID 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProjectID
        {
            get
            {
                return this._ProjectID;
            }
            set
            {
                this.OnProjectIDChanging(value);
                this._ProjectID = value;
                this.OnProjectIDChanged();
                this.OnPropertyChanged("ProjectID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProjectID;
        partial void OnProjectIDChanging(int value);
        partial void OnProjectIDChanged();
        /// <summary>
        /// 結構描述中沒有屬性 GroupID 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int GroupID
        {
            get
            {
                return this._GroupID;
            }
            set
            {
                this.OnGroupIDChanging(value);
                this._GroupID = value;
                this.OnGroupIDChanged();
                this.OnPropertyChanged("GroupID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _GroupID;
        partial void OnGroupIDChanging(int value);
        partial void OnGroupIDChanged();
        /// <summary>
        /// 結構描述中沒有屬性 GroupName 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string GroupName
        {
            get
            {
                return this._GroupName;
            }
            set
            {
                this.OnGroupNameChanging(value);
                this._GroupName = value;
                this.OnGroupNameChanged();
                this.OnPropertyChanged("GroupName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _GroupName;
        partial void OnGroupNameChanging(string value);
        partial void OnGroupNameChanged();
        /// <summary>
        /// 結構描述中沒有屬性 GroupPicture 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string GroupPicture
        {
            get
            {
                return this._GroupPicture;
            }
            set
            {
                this.OnGroupPictureChanging(value);
                this._GroupPicture = value;
                this.OnGroupPictureChanged();
                this.OnPropertyChanged("GroupPicture");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _GroupPicture;
        partial void OnGroupPictureChanging(string value);
        partial void OnGroupPictureChanged();
        /// <summary>
        /// 結構描述中沒有 tblProject 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public tblProject tblProject
        {
            get
            {
                return this._tblProject;
            }
            set
            {
                this._tblProject = value;
                this.OnPropertyChanged("tblProject");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private tblProject _tblProject;
        /// <summary>
        /// 結構描述中沒有 tblProjectGroupSection 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<tblProjectGroupSection> tblProjectGroupSection
        {
            get
            {
                return this._tblProjectGroupSection;
            }
            set
            {
                this._tblProjectGroupSection = value;
                this.OnPropertyChanged("tblProjectGroupSection");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<tblProjectGroupSection> _tblProjectGroupSection = new global::System.Data.Services.Client.DataServiceCollection<tblProjectGroupSection>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 結構描述中沒有 LEDProjecctModel.tblProjectGroupSection 的註解。
    /// </summary>
    /// <KeyProperties>
    /// ProjectID
    /// GroupID
    /// SectionID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("tblProjectGroupSection")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ProjectID", "GroupID", "SectionID")]
    public partial class tblProjectGroupSection : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 建立新的 tblProjectGroupSection 物件。
        /// </summary>
        /// <param name="projectID">ProjectID 的初始值。</param>
        /// <param name="groupID">GroupID 的初始值。</param>
        /// <param name="sectionID">SectionID 的初始值。</param>
        /// <param name="sectionName">SectionName 的初始值。</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static tblProjectGroupSection CreatetblProjectGroupSection(int projectID, int groupID, int sectionID, string sectionName)
        {
            tblProjectGroupSection tblProjectGroupSection = new tblProjectGroupSection();
            tblProjectGroupSection.ProjectID = projectID;
            tblProjectGroupSection.GroupID = groupID;
            tblProjectGroupSection.SectionID = sectionID;
            tblProjectGroupSection.SectionName = sectionName;
            return tblProjectGroupSection;
        }
        /// <summary>
        /// 結構描述中沒有屬性 ProjectID 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProjectID
        {
            get
            {
                return this._ProjectID;
            }
            set
            {
                this.OnProjectIDChanging(value);
                this._ProjectID = value;
                this.OnProjectIDChanged();
                this.OnPropertyChanged("ProjectID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProjectID;
        partial void OnProjectIDChanging(int value);
        partial void OnProjectIDChanged();
        /// <summary>
        /// 結構描述中沒有屬性 GroupID 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int GroupID
        {
            get
            {
                return this._GroupID;
            }
            set
            {
                this.OnGroupIDChanging(value);
                this._GroupID = value;
                this.OnGroupIDChanged();
                this.OnPropertyChanged("GroupID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _GroupID;
        partial void OnGroupIDChanging(int value);
        partial void OnGroupIDChanged();
        /// <summary>
        /// 結構描述中沒有屬性 SectionID 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SectionID
        {
            get
            {
                return this._SectionID;
            }
            set
            {
                this.OnSectionIDChanging(value);
                this._SectionID = value;
                this.OnSectionIDChanged();
                this.OnPropertyChanged("SectionID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SectionID;
        partial void OnSectionIDChanging(int value);
        partial void OnSectionIDChanged();
        /// <summary>
        /// 結構描述中沒有屬性 SectionName 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SectionName
        {
            get
            {
                return this._SectionName;
            }
            set
            {
                this.OnSectionNameChanging(value);
                this._SectionName = value;
                this.OnSectionNameChanged();
                this.OnPropertyChanged("SectionName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SectionName;
        partial void OnSectionNameChanging(string value);
        partial void OnSectionNameChanged();
        /// <summary>
        /// 結構描述中沒有 tblDevice 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<tblDevice> tblDevice
        {
            get
            {
                return this._tblDevice;
            }
            set
            {
                this._tblDevice = value;
                this.OnPropertyChanged("tblDevice");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<tblDevice> _tblDevice = new global::System.Data.Services.Client.DataServiceCollection<tblDevice>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// 結構描述中沒有 tblProjectGroup 的註解。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public tblProjectGroup tblProjectGroup
        {
            get
            {
                return this._tblProjectGroup;
            }
            set
            {
                this._tblProjectGroup = value;
                this.OnPropertyChanged("tblProjectGroup");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private tblProjectGroup _tblProjectGroup;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
